export const ADICIONA_PROJETOS = "ADICIONA_PROJETOS";
export const ALTERA_PROJETOS = "ALTERA_PROJETOS";
export const EXCLUIR_PROJETO = "EXCLUIR_PROJETO";
export const DEFINIR_PROJETO = "DEFINIR_PROJETO";

export const NOTIFICAR = "NOTIFICAR";